#!/bin/bash
set -euv

cd /
svn checkout http://llvm.org/svn/llvm-project/llvm/trunk/ llvm
cd /llvm/tools
svn checkout http://llvm.org/svn/llvm-project/cfe/trunk/ clang
cd /llvm/projects
svn checkout http://llvm.org/svn/llvm-project/compiler-rt/trunk/ compiler-rt
svn checkout http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
svn checkout http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi

cd /llvm
patch -p0 < /geordi/src/llvm-no-temp-files.patch

mkdir /llvm.build
cd /llvm.build
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_BUILD_DOCS=OFF /llvm
ninja
ninja install
ninja install-cxx install-cxxabi

rm -rf /llvm /llvm.build
